### ISSUE TITLE
Swiftlint implementation

### ISSUE THREAD

**Issue by lfarah** [Morbix/TableManager#10]
[Swiftlint](https://github.com/realm/SwiftLint) is an awesome tool to enforce Swift style and conventions.

**Comment by Morbix** [comment]
@lfarah I'm used to use Tailor.sh, do you know?

**Comment by lfarah** [comment]
Oh, I didn't know that one. I like Swiftlint because it's from Realm and the Realm team is amazing

**Comment by Morbix** [comment]
@lfarah Swiftlint finally added.

**Comment by lfarah** [comment]
![parrot](https://cloud.githubusercontent.com/assets/6511079/21504351/472fdd34-cc45-11e6-9239-295f4528cd35.gif)
