### ISSUE TITLE
Create a JSON connection to show response

### ISSUE THREAD

**Issue by Morbix** [Morbix/TableManager#29]
Suggestion by @ricardorauber

**Comment by SuperWomble** [comment]
IMO, these feature requests (JSON, Core Data etc.) are beyond the scope of the project. Generally, it's preferably that a library's scope be as minimal and restrained as possible. This makes it easier to maintain, and to use without dependencies. One of the key benefits of your library is that it is simple to use, and also simple to understand.

**Comment by Morbix** [comment]
I agree with you. Thanks for the feedback.

It would be in another pod, like a TableManagerConections. What you think?

Enviado do meu iPhone

Em 23 de abr de 2017, às 00:33, SuperWomble <notifications@github.com<mailto:notifications@github.com>> escreveu:


IMO these feature requests (JSON, Core Data etc.) are beyond the scope of the project. Generally, it's preferably that a library be restrained in it scope.

**Comment by SuperWomble** [comment]
I think that would be a good idea. Big cheers.
