### ISSUE TITLE
indexPathsForVisibleRows

### ISSUE THREAD

**Issue by lfarah** [Morbix/TableManager#6]
implement `indexPathsForVisibleRows` so we can call `table.firstCell()`, `table.lastCell` and `table.middleCell()`

**Comment by Morbix** [comment]
@lfarah I released a new version (1.1.0) with:
- `selectedRow()` method in TableManger class;
- `displayedRows()` method in TableManger class;

**Comment by lfarah** [comment]
.displayedRows() is a little bit off
<img width="668" alt="screen shot 2016-06-05 at 5 15 26 pm" src="https://cloud.githubusercontent.com/assets/6511079/15809225/1ee418a4-2b41-11e6-92ad-403cc43816f0.png">

**Comment by Morbix** [comment]
@lfarah it is correct, because the first cell was not recycled yet. Even when it is behind the header/footer the table holds the cell. Try remove the header/footer configuration from the example project and test again.

**Comment by Morbix** [comment]
![captura de tela 2016-06-11 as 17 24 21](https://cloud.githubusercontent.com/assets/590584/15987282/7d07894a-2ff9-11e6-8b79-2be070af8cf3.png)

**Comment by lfarah** [comment]
So should we remove the first element of the array so we have the correct number of **visible cells**?

**Comment by Morbix** [comment]
Off course not. The number is correct. I'm using the Apple's framework:
![captura de tela 2016-06-11 as 17 35 44](https://cloud.githubusercontent.com/assets/590584/15987328/04ff7ad2-2ffb-11e6-99ef-092ab8f6f575.png)

If you run direclty `tableView.indexPathsForVisibleRows.first` you will see the same case. With or without TableManager.

**Comment by lfarah** [comment]
Makes total sense!

**Comment by lfarah** [comment]
So can we close this?

**Comment by Morbix** [comment]
Yeah! :)
