### ISSUE TITLE
Carthage Compatibility

### ISSUE THREAD

**Issue by lfarah** [Morbix/TableManager#8]
[Instructions here](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)

**Comment by cleberhenriques** [comment]
Hello @lfarah and @Morbix, here is a brand new pull request that adds carthage compatibility with TableManager. https://github.com/Morbix/TableManager/pull/39

**Comment by lfarah** [comment]
Damn you're  **awesome**!

**Comment by Morbix** [comment]
Done in #46 by @bruno-rocha-movile!!
